version: '3'

services:
  backup:
    image: weseek/mongodb-awesome-backup:0.6.3
    environment:
      - CRONMODE=true
      - CRON_EXPRESSION=0 4 * * *                               # change it
      # - AWS_ACCESS_KEY_ID=${Your IAM Access Key ID}           # change it
      # - AWS_SECRET_ACCESS_KEY=${Your IAM Secret Access Key}   # change it
      # - TARGET_BUCKET_URL=s3://${Your Bucket Name}/        # change it
    links:
      - mongo:mongo
    restart: unless-stopped
