http:
  routers:
    zabbix:
      rule: "Host(`zabbix-web.gtc.ce.ac.bw`)"
      service: zabbix
      entryPoints:
        - http

    growi:
      rule: "Host(`growi.gtc.ce.ac.bw`)"
      service: growi
      entryPoints:
        - http

  services:
    zabbix-web:
      loadBalancer:
        servers:
          - url: "http://zabbix-web:8081"

    growi:
      loadBalancer:
        servers:
          - url: "http://growi:3000"

