services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=securepassword
    volumes:
      - ./data:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./certs:/usr/local/share/ca-certificates/gtc
    entrypoint: >
      sh -c "cp -r /usr/local/share/ca-certificates/gtc /usr/share/ca-certificates/gtc &&
            update-ca-certificates &&
            apache2-foreground"

    depends_on:
      - nextcloud-db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.gtc.ce.ac.bw`)"
      - "traefik.http.routers.nextcloud.entrypoints=websecure"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https" # リダイレクト用
    networks:
      traefik_network:
        ipv4_address: 192.168.100.51

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=securepassword
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      traefik_network:
        ipv4_address: 192.168.100.61

  self-service-password:
    image: my-custom-php
    container_name: self-service-password
    environment:
      LDAP_URL: "ldap://staffdc2.staff.gtc.ce.ac.bw"
      LDAP_BINDDN: "CN=Administrator,DC=staff,DC=gtc,DC=ce,DC=ac,DC=bw"
      LDAP_BINDPW: "Password1"
      LDAP_BASE: "DC=staff,DC=gtc,DC=ce,DC=ac,DC=bw"
      MAIL_SMTP_SERVER: "mail.gtc.ce.ac.bw"
      MAIL_FROM: "noreply@gtc.ce.ac.bw"
    volumes:
      - ./ssp-conf/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./ssp-conf/config.inc.php:/var/www/conf/config.inc.php
      - ./ssp-conf/ldap_config.php:/var/www/conf/ldap_config.php
      - ./templates:/var/www/templates
      - ./www/htdocs:/var/www/html
      - ./www/lib:/var/www/lib
      - ./www/conf:/var/www/conf
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.ssp.rule=Host(`ssp.gtc.ce.ac.bw`)"
      - "traefik.http.routers.ssp.entrypoints=websecure"
      - "traefik.http.routers.ssp.tls=true"
      - "traefik.http.services.ssp.loadbalancer.server.port=80"
      - "traefik.http.middlewares.redirect-to-https.redirectScheme.scheme=https" # リダイレクト用
    networks:
      traefik_network:
        ipv4_address: 192.168.100.62

  collabora-online:
    image: collabora/code
    container_name: collabora-online
    restart: unless-stopped
    environment:
      - domain=nextcloud\\.gtc\\.ce\\.ac\\.bw
      - server_name=collabora.gtc.ce.ac.bw
      - extra_params=--o:ssl.termination=true --o:ssl.enable=false --o:welcome.enable=false --o:net.post_allow.host=nextcloud.gtc.ce.ac.bw
    networks:
      traefik_network:
        ipv4_address: 192.168.100.52
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.collabora.rule=Host(`collabora.gtc.ce.ac.bw`)"
      - "traefik.http.routers.collabora.entrypoints=websecure"
      - "traefik.http.routers.collabora.tls=true"
      - "traefik.http.services.collabora.loadbalancer.server.port=9980"

networks:
  traefik_network:
    external: true
    name: zabbix-growi_traefik_network

