services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=securepassword
    volumes:
      - ./data:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf

    depends_on:
      - nextcloud-db
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik_network"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.gtc.ce.ac.bw`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    networks:
      - traefik_network

  nextcloud-db:
    image: mariadb:latest
    container_name: nextcloud-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=securepassword
    restart: unless-stopped
    volumes:
      - ./db_data:/var/lib/mysql

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
    name: zabbix-growi_traefik_network

