FROM ltbproject/self-service-password:latest

# 必要なパッケージをインストール（プロキシ設定を追加）
ENV COMPOSER_ALLOW_SUPERUSER=1
ENV COMPOSER_NO_INTERACTION=1
ENV HTTP_PROXY=http://10.97.12.1:3128
ENV HTTPS_PROXY=http://10.97.12.1:3128

# 必要なパッケージをインストール
# 必要なパッケージをインストールして MySQL 拡張を追加
RUN apt-get update && \
    apt-get install -y curl php-cli unzip git zip php-xml php-mbstring php-curl php-zip php-mysql php-ldap php-tokenizer php-json php-common \
    libmariadb-dev libmariadb-dev-compat libzip-dev build-essential ldap-utils ca-certificates && \
    docker-php-ext-install mysqli pdo pdo_mysql zip && \
    docker-php-ext-enable mysqli pdo pdo_mysql zip && \
    curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# コンテナのデフォルトディレクトリ
WORKDIR /var/www/htdocs

# コンテナ内でPHPのバージョン確認
RUN php -v

# ポート80を公開（必要であれば）
EXPOSE 80


# 準備ができたらカスタムスクリプトやファイルをコンテナにコピー
#COPY ./ssp-conf/index.php /var/www/htdocs/index.php
RUN rm -rf /var/www/htdocs/index.php
RUN rm -rf /var/www/htdocs/changecustompwdfield.php
RUN rm -rf /var/www/htdocs/changesshkey.php
RUN rm -rf /var/www/htdocs/newcaptcha.php        
RUN rm -rf /var/www/htdocs/resetbytoken.php   
RUN rm -rf /var/www/htdocs/setquestions.php
RUN rm -rf /var/www/htdocs/change.php           
RUN rm -rf /var/www/htdocs/checkentropy.php          
RUN rm -rf /var/www/htdocs/resetbyquestions.php  
RUN rm -rf /var/www/htdocs/setattributes.php
RUN rm -rf /var/www/htdocs/sendtoken.php      
RUN rm -rf /var/www/htdocs/sendsms.php
RUN rm -rf /var/www/htdocs/setquestions.php
RUN rm -rf /var/www/htdocs/vendor 
RUN rm -rf  /var/www/vendor
RUN ln -s /var/www/htdocs/reset_request.php /var/www/htdocs/index.php

RUN mkdir /etc/ldap
COPY ./www/htdocs/composer.json /var/www/htdocs/composer.json
COPY ./www/htdocs/ldap_config.php /var/www/conf/ldap_config.php
COPY ./www/htdocs/reset_request.php /var/www/htdocs/reset_request.php
COPY ./www/htdocs/reset_password.php /var/www/htdocs/reset_password.php
COPY ./www/htdocs/admin_dashboard.php /var/www/htdocs/admin_dashboard.php
COPY ./www/htdocs/change_password.php /var/www/htdocs/change_password.php
COPY ./www/htdocs/ldap_user_import.php /var/www/htdocs/ldap_user_import.php
COPY ./www/htdocs/vendor /var/www/htdocs/vendor
COPY ./templates/reset_request.tpl /var/www/templates/reset_request.tpl
COPY ./templates/admin_dashboard.tpl /var/www/templates/admin_dashboard.tpl
COPY ./templates/change_password.tpl /var/www/templates/change_password.tpl
COPY ./templates/ldap_user_import.tpl /var/www/templates/ldap_user_import.tpl
COPY ./templates/header.tpl /var/www/templates/header.tpl
COPY ./templates/footer.tpl /var/www/templates/footer.tpl
COPY ./css/navilink.css /var/www/htdocs/css/navilink.css
COPY ./certs/gtc-RootCA.crt /usr/local/share/ca-certificates/
COPY ./certs/staff-STAFFDC2-CA.crt /usr/local/share/ca-certificates/
COPY ./etc/ldap/ldap.conf /etc/ldap/ldap.conf
RUN update-ca-certificates


RUN echo $PATH
# Composer のインストール
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Composer グローバルにプロキシを設定
RUN /usr/local/bin/composer config -g repo.packagist composer https://repo.packagist.org
RUN /usr/local/bin/composer install --no-dev --prefer-dist --optimize-autoloader
RUN /usr/local/bin/composer require phpoffice/phpspreadsheet


# 確認用
RUN php -r "echo 'PhpSpreadsheet loaded: ' . (class_exists('\PhpOffice\PhpSpreadsheet\IOFactory') ? 'Yes' : 'No') . PHP_EOL;"
